/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Visao;
import Controle.ContratosC;
import Modelo.ContratoM;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class AtualizarContratoV extends javax.swing.JInternalFrame {
private ContratosC controlador = new ContratosC();
    private int idContratoAtual;

    /**
     * Creates new form AtualizarContratoV
     */
    public AtualizarContratoV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTDatainicio = new javax.swing.JTextField();
        jTDatatermino = new javax.swing.JTextField();
        jTValor = new javax.swing.JTextField();
        jTIDInquilino = new javax.swing.JTextField();
        jTIDPropriedade = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTDiadeVencimento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTIDContrato = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jTDatainicio.setColumns(10);

        jTDatatermino.setColumns(10);

        jTValor.setColumns(10);

        jTIDInquilino.setColumns(10);

        jTIDPropriedade.setColumns(10);

        jButton1.setText("Atualizar Informacoes Contrato");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarContrato(evt);
            }
        });

        jLabel1.setText("Dia de vencimento:");

        jTDiadeVencimento.setColumns(10);

        jLabel2.setText("Data Inicio:");

        jLabel3.setText("Data Fim");

        jLabel4.setText("Valor:");

        jLabel5.setText("ID Inquilino");

        jLabel6.setText("Id Propriedade");

        jButton2.setText("Busca Contrato");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaContrato(evt);
            }
        });

        jLabel7.setText("ID contrato");

        jTIDContrato.setColumns(10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTDiadeVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTIDPropriedade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTIDInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTDatatermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTDatainicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTIDContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel7)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTIDContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTDatainicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTDatatermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTIDInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTIDPropriedade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTDiadeVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscaContrato(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaContrato
    try {
        // Obter o ID do contrato do campo de texto
        String idStr = jTIDContrato.getText().trim();
        
        if (idStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o ID do contrato!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        idContratoAtual = Integer.parseInt(idStr);
        ResultSet rs = controlador.consultarContrato(idContratoAtual);
        
        if (rs != null && rs.next()) {
            jTDatainicio.setText(rs.getString("data_inicio"));
            jTDatatermino.setText(rs.getString("data_fim"));
            jTValor.setText(rs.getString("valor"));
            jTIDInquilino.setText(rs.getString("id_inquilino"));
            jTIDPropriedade.setText(rs.getString("id_propriedade"));
            jTDiadeVencimento.setText(rs.getString("dia_vencimento"));
        } else {
            JOptionPane.showMessageDialog(this, "Contrato não encontrado!", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID inválido! Deve ser um número.", "Erro", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_BuscaContrato

    private void atualizarContrato(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarContrato
 try {
            // Obter valores dos campos
            String dataInicio = jTDatainicio.getText().trim();
            String dataTermino = jTDatatermino.getText().trim();
            String valor = jTValor.getText().trim();
            String idInquilino = jTIDInquilino.getText().trim();
            String idPropriedade = jTIDPropriedade.getText().trim();
            String diaVencimento = jTDiadeVencimento.getText().trim();

            // Validações básicas
            if (dataInicio.isEmpty() || valor.isEmpty() || idInquilino.isEmpty() || 
                idPropriedade.isEmpty() || diaVencimento.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Todos os campos são obrigatórios!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                // Converter valores para os tipos corretos
                double valorDouble = Double.parseDouble(valor);
                int idInquilinoInt = Integer.parseInt(idInquilino);
                int idPropriedadeInt = Integer.parseInt(idPropriedade);
                int diaVencimentoInt = Integer.parseInt(diaVencimento);
                
                // Criar objeto Contrato
                ContratoM contrato = new ContratoM();
                contrato.setDataInicio(dataInicio);
                contrato.setDataFim(dataTermino);
                contrato.setValor(valorDouble);
                contrato.setIdInquilino(idInquilinoInt);
                contrato.setIdPropriedade(idPropriedadeInt);
                contrato.setDiaVencimento(diaVencimentoInt);

                // Chamar controle para atualizar
                controlador.atualizarContrato(idContratoAtual, contrato);
                
                
                    JOptionPane.showMessageDialog(this, "Contrato atualizado com sucesso!");
                
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Valores numéricos inválidos!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }    }//GEN-LAST:event_atualizarContrato
                                                

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTDatainicio;
    private javax.swing.JTextField jTDatatermino;
    private javax.swing.JTextField jTDiadeVencimento;
    private javax.swing.JTextField jTIDContrato;
    private javax.swing.JTextField jTIDInquilino;
    private javax.swing.JTextField jTIDPropriedade;
    private javax.swing.JTextField jTValor;
    // End of variables declaration//GEN-END:variables
}
