/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Visao;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import Controle.PropriedadesC;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;

public class ListadePropriedadeV extends javax.swing.JInternalFrame {

    private javax.swing.JTable JListaPropriedade;
    private DefaultTableModel ListaPropriedade;

    public ListadePropriedadeV() {
        initComponents();
        
        ListaPropriedade = new DefaultTableModel(
            new Object[][]{},
            new String[]{
                "ID", "Proprietário", "Endereço", "Tipo", 
                "Valor Aluguel", "Área (m²)", "Quartos", 
                "Banheiros", "Vagas", "Data Cadastro", "Disponível"
            }
        ) {
            Class[] types = new Class[]{
                Integer.class, String.class, String.class, 
                String.class, Double.class, Double.class, 
                Integer.class, Integer.class, Integer.class, 
                String.class, Boolean.class
            };
            
            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
            
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        JListaPropriedade = new javax.swing.JTable(ListaPropriedade);
        JListaPropriedade.setAutoCreateRowSorter(true);
        JListaPropriedade.getTableHeader().setReorderingAllowed(false);
        
        jScrollPane1.setViewportView(JListaPropriedade);
        
        carregarDados();
    }

    private void carregarDados() {
        PropriedadesC dados = new PropriedadesC();
        ResultSet listaPropriedades = null;
        
        try {
            listaPropriedades = dados.consultarTodasPropriedades();
            int j = 0;
            
            while(listaPropriedades.next()) {
                ListaPropriedade.setRowCount(j+1);
                
                for(int i = 1; i <= 11; i++) {
                    if(i == 11) { // Coluna "Disponível" (booleana)
                        JListaPropriedade.setValueAt(listaPropriedades.getBoolean(i), j, i-1);
                    }
                    else if(i == 1) { // Coluna "ID" (inteiro)
                        JListaPropriedade.setValueAt(listaPropriedades.getInt(i), j, i-1);
                    }
                    else if(i == 5 || i == 6 || i == 7 || i == 8) { // Colunas numéricas
                        if(i == 5) { // Valor Aluguel
                            JListaPropriedade.setValueAt(listaPropriedades.getDouble(i), j, i-1);
                        }
                        else if(i == 6) { // Área
                            JListaPropriedade.setValueAt(listaPropriedades.getDouble(i), j, i-1);
                        }
                        else { // Quartos, Banheiros, Vagas
                            JListaPropriedade.setValueAt(listaPropriedades.getInt(i), j, i-1);
                        }
                    }
                    else { // Demais colunas (strings)
                        JListaPropriedade.setValueAt(listaPropriedades.getString(i), j, i-1);
                    }
                }
                j++;
            }
        } catch(Exception er) {
            er.printStackTrace();
            JOptionPane.showMessageDialog(this, 
                "Erro ao carregar propriedades: " + er.getMessage(),
                "Erro", JOptionPane.ERROR_MESSAGE);
        } finally {
            if(listaPropriedades != null) {
                try {
                    listaPropriedades.close();
                } catch(SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
