/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Visao;

import javax.swing.table.DefaultTableModel;

public class ListadePropriedadeV extends javax.swing.JInternalFrame {

    private javax.swing.JTable JListaPropriedade;
    private DefaultTableModel ListaPropriedade;

    public ListadePropriedadeV() {
        initComponents();
        
        ListaPropriedade = new DefaultTableModel(
            new Object[][]{},
            new String[]{
                "ID", 
                "Proprietário", 
                "Endereço", 
                "Tipo", 
                "Valor Aluguel", 
                "Área (m²)", 
                "Quartos", 
                "Banheiros", 
                "Vagas", 
                "Data Cadastro", 
                "Disponível"
            }
        ) {
            Class[] types = new Class[]{
                java.lang.Integer.class,   // ID
                java.lang.String.class,    // Proprietário
                java.lang.String.class,   // Endereço
                java.lang.String.class,    // Tipo
                java.lang.Double.class,    // Valor Aluguel
                java.lang.Double.class,    // Área
                java.lang.Integer.class,   // Quartos
                java.lang.Integer.class,   // Banheiros
                java.lang.Integer.class,   // Vagas
                java.lang.String.class,    // Data Cadastro
                java.lang.Boolean.class    // Disponível
            };
            
            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
            
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Torna a tabela não editável
            }
        };
        
        JListaPropriedade = new javax.swing.JTable(ListaPropriedade);
        
        // Configurações adicionais da tabela
        JListaPropriedade.setAutoCreateRowSorter(true);
        JListaPropriedade.getTableHeader().setReorderingAllowed(false);
        
        jScrollPane1.setViewportView(JListaPropriedade);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
