/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Visao;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class ListadeInquilinoV extends javax.swing.JInternalFrame {

private JTable JListaInquilino;
private DefaultTableModel ListaInquilino;


    public ListadeInquilinoV() {
        initComponents();
        ListaInquilino = new DefaultTableModel(
        new Object [][] {},
        new String [] {"ID", 
        "Nome Completo", 
        "CPF", 
        "RG", 
        "Data Nascimento", 
        "Telefone", 
        "Email", 
        "Profissão", 
        "Renda Mensal", 
        "Estado Civil", 
        "Data Cadastro", 
        "Ativo"}
    ) {
        Class[] types = new Class[]{
        java.lang.Integer.class,   // ID
        java.lang.String.class,    // Nome
        java.lang.String.class,    // CPF
        java.lang.String.class,    // RG
        java.lang.String.class,    // Data Nascimento (ou Date.class se preferir)
        java.lang.String.class,    // Telefone
        java.lang.String.class,    // Email
        java.lang.String.class,    // Profissão
        java.lang.Double.class,    // Renda Mensal
        java.lang.String.class,    // Estado Civil
        java.lang.String.class,    // Data Cadastro (ou Date.class)
        java.lang.Boolean.class    // Ativo
        };
        
        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }
    };
JListaInquilino = new javax.swing.JTable(ListaInquilino);
jScrollPane1.setViewportView(JListaInquilino);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
