/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Visao;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ListadeDonoImovelV extends javax.swing.JInternalFrame {

    private JTable JListaDonoImovel;
    private DefaultTableModel ListaDonoImovel;

    /**
     * Creates new form ListadeDonoImovelV
     */
    public ListadeDonoImovelV() {
        initComponents();
        ListaDonoImovel = new DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "ID",
                    "Nome Completo",
                    "CPF",
                    "RG",
                    "Telefone",
                    "Email",
                    "Endereco",
                    "Banco",
                    "Agencia",
                    "Conta",
                    "Tipo de conta",
                    "Data de cadastro",
                    "Ativo"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.Integer.class, // ID
                java.lang.String.class, // Nome
                java.lang.String.class, // CPF/CNPJ
                java.lang.String.class, // RG/IE
                java.lang.String.class, // Telefone
                java.lang.String.class, // Email
                java.lang.String.class, // Endereço
                java.lang.String.class, // Banco
                java.lang.String.class, // Agência
                java.lang.String.class, // Conta
                java.lang.String.class, // Tipo de conta
                java.lang.String.class, // Data de cadastro
                java.lang.Boolean.class // Ativo
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        };
        JListaDonoImovel = new javax.swing.JTable(ListaDonoImovel);
        jScrollPane1.setViewportView(JListaDonoImovel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
