/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Visao;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import Controle.inquilinosC;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;

public class ListadeInquilinoV extends javax.swing.JInternalFrame {

    private javax.swing.JTable JListaInquilino;
    private DefaultTableModel ListaInquilino;

    public ListadeInquilinoV() {
        initComponents();
        
        // Configuração do modelo da tabela
        ListaInquilino = new DefaultTableModel(
            new Object [][] {},
            new String [] {
                "ID", "Nome Completo", "CPF", "RG", 
                "Data Nascimento", "Telefone", "Email", 
                "Profissão", "Renda Mensal", "Estado Civil", 
                "Data Cadastro", "Ativo"
            }
        ) {
            Class[] types = new Class[]{
                Integer.class, String.class, String.class, 
                String.class, String.class, String.class, 
                String.class, String.class, Double.class, 
                String.class, String.class, Boolean.class
            };
            
            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        };

        JListaInquilino = new javax.swing.JTable(ListaInquilino);
        jScrollPane1.setViewportView(JListaInquilino);
    
        carregarDados();
    }

    private void carregarDados() {
        inquilinosC dados = new inquilinosC();
        ResultSet listaInquilinos = null;
        
        try {
    listaInquilinos = dados.consultarTodosInquilinos();
    // Contador de linhas da JTable
    int j = 0;
    
    while(listaInquilinos.next()) {
        ListaInquilino.setRowCount(j+1);
        
        for(int i = 1; i <= 12; i++) {
            if(i == 12) { // Coluna "Ativo" (booleana)
                JListaInquilino.setValueAt(listaInquilinos.getBoolean(i), j, i-1);
            }
            else if(i == 1) { // Coluna "ID" (inteiro)
                JListaInquilino.setValueAt(listaInquilinos.getInt(i), j, i-1);
            }
            else if(i == 9) { // Coluna "Renda Mensal" (double)
                JListaInquilino.setValueAt(listaInquilinos.getDouble(i), j, i-1);
            }
            else { // Demais colunas (strings)
                JListaInquilino.setValueAt(listaInquilinos.getString(i), j, i-1);
            }
        }
        j++;
    }
} catch(Exception er) {
    er.printStackTrace();
    JOptionPane.showMessageDialog(this, 
        "Erro ao carregar dados: " + er.getMessage(),
        "Erro", JOptionPane.ERROR_MESSAGE);
} finally {
    if(listaInquilinos != null) {
        try {
            listaInquilinos.close();
        } catch(SQLException e) {
            e.printStackTrace();
        }
    }
}
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
